#!/usr/bin/env python3
"""
Generate Dockerfile.generated by combining:
  - Dockerfile.builder (our Jetson builder stage)
  - The prod stage from the upstream immich Dockerfile

The upstream prod stage is adjusted for Jetson:
  - FROM line replaced with FROM ${PROD_BASE_IMAGE} AS prod
  - ARG DEVICE removed (we always target cuda)
  - The DEVICE-conditional in the apt-get install RUN expanded to libmimalloc2.0
  - ENV lines from prod-cuda prepended (LD_PRELOAD, MACHINE_LEARNING_MODEL_ARENA)
"""

import argparse
import sys


def parse_stages(lines):
    """Split Dockerfile lines into a list of (header_line, body_lines) per stage."""
    stages = []
    current_header = None
    current_body = []
    for line in lines:
        if line.lstrip().startswith("FROM "):
            if current_header is not None:
                stages.append((current_header, current_body))
            current_header = line
            current_body = []
        else:
            if current_header is not None:
                current_body.append(line)
    if current_header is not None:
        stages.append((current_header, current_body))
    return stages


def stage_name(header):
    """Extract the AS name from a FROM line, e.g. 'AS prod-cuda' -> 'prod-cuda'."""
    parts = header.split()
    for i, p in enumerate(parts):
        if p.upper() == "AS" and i + 1 < len(parts):
            return parts[i + 1].strip()
    return None


def extract_env_lines(body_lines):
    """
    Return the ENV instruction lines from a stage body.
    Handles multi-line ENV blocks (lines ending with backslash).
    """
    env_lines = []
    in_env = False
    for line in body_lines:
        stripped = line.rstrip()
        if stripped.lstrip().startswith("ENV "):
            in_env = True
            env_lines.append(line)
        elif in_env:
            env_lines.append(line)
            if not stripped.endswith("\\"):
                in_env = False
    return env_lines


DEVICE_CONDITIONAL = (
    "$(if ! [ \"$DEVICE\" = \"openvino\" ] && "
    "! [ \"$DEVICE\" = \"rocm\" ]; then echo \"libmimalloc2.0\"; fi)"
)


def adjust_prod_body(body_lines):
    """
    Adjust the upstream prod stage body for Jetson/cuda:
      - Drop ARG DEVICE
      - Expand the DEVICE-conditional to the literal package name
      - Hardcode DEVICE=cuda (ARG DEVICE was removed so ${DEVICE} would be empty)
    """
    result = []
    for line in body_lines:
        # Drop ARG DEVICE
        if line.strip() == "ARG DEVICE":
            continue
        # Expand DEVICE-conditional to literal libmimalloc2.0
        if DEVICE_CONDITIONAL in line:
            line = line.replace(DEVICE_CONDITIONAL, "libmimalloc2.0")
        # Hardcode DEVICE=cuda (ARG DEVICE was removed)
        if "DEVICE=${DEVICE}" in line:
            line = line.replace("DEVICE=${DEVICE}", "DEVICE=cuda")
        result.append(line)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--builder", required=True, help="Path to Dockerfile.builder (builder template)")
    parser.add_argument("--upstream", required=True, help="Path to upstream immich Dockerfile")
    parser.add_argument("--version", required=True, help="Immich version tag (e.g. v2.7.4)")
    parser.add_argument("--output", required=True, help="Output path for generated Dockerfile")
    args = parser.parse_args()

    with open(args.builder) as f:
        builder_content = f.read()

    with open(args.upstream) as f:
        upstream_lines = f.readlines()

    stages = parse_stages(upstream_lines)

    # Extract ENV lines from prod-cuda (LD_PRELOAD, MACHINE_LEARNING_MODEL_ARENA)
    prod_cuda_envs = []
    for header, body in stages:
        if stage_name(header) == "prod-cuda":
            prod_cuda_envs = extract_env_lines(body)
            break

    if not prod_cuda_envs:
        print("WARNING: prod-cuda stage not found or has no ENV instructions", file=sys.stderr)

    # Find the final prod stage
    prod_body = None
    for header, body in stages:
        if stage_name(header) == "prod":
            prod_body = body
            break

    if prod_body is None:
        print("ERROR: could not find 'AS prod' stage in upstream Dockerfile", file=sys.stderr)
        sys.exit(1)

    prod_body = adjust_prod_body(prod_body)

    with open(args.output, "w") as f:
        f.write(f"# Generated by scripts/generate_dockerfile.py — do not edit\n")
        f.write(f"# Upstream immich: {args.version}\n")
        f.write("\n")
        f.write(builder_content.rstrip("\n"))
        f.write("\n\n")
        f.write("FROM ${PROD_BASE_IMAGE} AS prod\n")
        if prod_cuda_envs:
            f.writelines(prod_cuda_envs)
        f.writelines(prod_body)

    print(f"==> Generated {args.output} (upstream immich {args.version})")


if __name__ == "__main__":
    main()
